name: Tests-conda

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: latest supported versions
            os: ubuntu-latest
            python-version: '3.10'

          - name: oldest supported versions
            os: ubuntu-latest
            python-version: '3.7'
            toxenv: py37-test-oldest

          - name: macOS 11
            os: macos-11
            python-version: '3.10'
            toxenv: py310-test-latest

    steps:
      - name: Install Conda w/ Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
      - name: Install Dependencies
        shell: bash -el {0}
        run: |
          conda install tox
      - name: Run Tests
        shell: bash -el {0}
        run: |
          tox --version