name: Tests-conda

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - name: latest supported versions
            os: ubuntu-latest
            python-version: '3.10'

          - name: oldest supported versions
            os: ubuntu-latest
            python-version: '3.7'
            toxenv: py37-test-oldest

          - name: macOS 11
            os: macos-11
            python-version: '3.10'
            toxenv: py310-test-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda w/ Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: soliket-tests
          environment-file: soliket-tests.yml
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          use-mamba: true
          miniforge-variant: Mambaforge
      - name: Install class
        shell: bash -el {0}
        run: |
          if [[ ${MATRIX_OS} == "macos-11" ]]; then
            export LDFLAGS="-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib"
            . install_class_osx.sh
          fi
        env:
          MATRIX_OS: ${{ matrix.os }}
      - name: Run Tox
        shell: bash -el {0}
        run: |
          tox --version
      - name: Run Cobaya
        shell: bash -el {0}
        run: |
          python -c "import cobaya; print(cobaya.__version__)"
